### PR TITLE
adding <div>

### PR DESCRIPTION
**Pull request by Dion-M-Sato**
I noticed that this file is not validated. Following TEI P5, I added `<div>` tag. The structure is here&nbsp;: `<div><head><p></p></head></div>`. This minor change made it validated.

### CODE REVIEW

**Comment by kzhr** [comment]
I don't see the modification is meaningful: the head element can be contained by the body element, and it can be multiple (see https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-head.html and https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD). I am not opposed to merge, but feel some weirdness....

**Comment by somiyagawa** [comment]
I see. Yeah, it is seemingly not so meaningful anyway, but perhaps
`<div><head></head><p></p></div>` shows the relation between the
`<head>` tag and the `<p>` tag? Like this `<head>`section title
`</head>` is the title of `<p>main text</p>` .

**Comment by somiyagawa** [comment]
Seeing examples like the one below from https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD, I think the use of `<div>` is OK. But I wonder how many contexts <head> can be used in, seeing https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD. I guess that's why you felt weird. Also it's super weird from the HTML point of view ;)

 `<div2 type="chapter" n="2" xml:id="JA0102">`
  `<head>Of Mr. Joseph Andrews, his birth, parentage, education, and great
     endowments; with a word or two concerning ancestors.</head>`
 ` <p>Mr. Joseph Andrews, the hero of our ensuing history, was esteemed to
     be the only son of Gaffar and Gammar Andrews, and brother to the
     illustrious Pamela, whose virtue is at present so famous ... </p>`
`<!-- remainder of chapter 2 here -->`
 `</div2>` (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/DS.html#DSHD)

**Comment by kzhr** [comment]
Surely using div makes an encoding structure clearer: that's why I'm not opposed to this request. No matter how this is weird, it's a good practice to limit one head to one element in most cases. So to close #7 .

**Pull request merged**
